/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as BoardNews_listRouteImport } from './routes/board/news_list'
import { Route as PagesBrandRouteImport } from './routes/pages/brand'
import { Route as PagesChangeinfoRouteImport } from './routes/pages/changeinfo'
import { Route as PagesContactRouteImport } from './routes/pages/contact'
import { Route as PagesDocnormalRouteImport } from './routes/pages/docnormal'
import { Route as PagesDocspecialRouteImport } from './routes/pages/docspecial'
import { Route as PagesLocationRouteImport } from './routes/pages/location'
import { Route as PagesOverviewRouteImport } from './routes/pages/overview'
import { Route as PagesPremiumRouteImport } from './routes/pages/premium'
import { Route as PagesVideoRouteImport } from './routes/pages/video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardNews_listRoute = BoardNews_listRouteImport.update({
  id: '/board/news_list',
  path: '/board/news_list',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesBrandRoute = PagesBrandRouteImport.update({
  id: '/pages/brand',
  path: '/pages/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesChangeinfoRoute = PagesChangeinfoRouteImport.update({
  id: '/pages/changeinfo',
  path: '/pages/changeinfo',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesContactRoute = PagesContactRouteImport.update({
  id: '/pages/contact',
  path: '/pages/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesDocnormalRoute = PagesDocnormalRouteImport.update({
  id: '/pages/docnormal',
  path: '/pages/docnormal',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesDocspecialRoute = PagesDocspecialRouteImport.update({
  id: '/pages/docspecial',
  path: '/pages/docspecial',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesLocationRoute = PagesLocationRouteImport.update({
  id: '/pages/location',
  path: '/pages/location',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesOverviewRoute = PagesOverviewRouteImport.update({
  id: '/pages/overview',
  path: '/pages/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPremiumRoute = PagesPremiumRouteImport.update({
  id: '/pages/premium',
  path: '/pages/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesVideoRoute = PagesVideoRouteImport.update({
  id: '/pages/video',
  path: '/pages/video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/board/news_list': typeof BoardNews_listRoute
  '/pages/brand': typeof PagesBrandRoute
  '/pages/changeinfo': typeof PagesChangeinfoRoute
  '/pages/contact': typeof PagesContactRoute
  '/pages/docnormal': typeof PagesDocnormalRoute
  '/pages/docspecial': typeof PagesDocspecialRoute
  '/pages/location': typeof PagesLocationRoute
  '/pages/overview': typeof PagesOverviewRoute
  '/pages/premium': typeof PagesPremiumRoute
  '/pages/video': typeof PagesVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/board/news_list': typeof BoardNews_listRoute
  '/pages/brand': typeof PagesBrandRoute
  '/pages/changeinfo': typeof PagesChangeinfoRoute
  '/pages/contact': typeof PagesContactRoute
  '/pages/docnormal': typeof PagesDocnormalRoute
  '/pages/docspecial': typeof PagesDocspecialRoute
  '/pages/location': typeof PagesLocationRoute
  '/pages/overview': typeof PagesOverviewRoute
  '/pages/premium': typeof PagesPremiumRoute
  '/pages/video': typeof PagesVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/board/news_list': typeof BoardNews_listRoute
  '/pages/brand': typeof PagesBrandRoute
  '/pages/changeinfo': typeof PagesChangeinfoRoute
  '/pages/contact': typeof PagesContactRoute
  '/pages/docnormal': typeof PagesDocnormalRoute
  '/pages/docspecial': typeof PagesDocspecialRoute
  '/pages/location': typeof PagesLocationRoute
  '/pages/overview': typeof PagesOverviewRoute
  '/pages/premium': typeof PagesPremiumRoute
  '/pages/video': typeof PagesVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/board/news_list'
    | '/pages/brand'
    | '/pages/changeinfo'
    | '/pages/contact'
    | '/pages/docnormal'
    | '/pages/docspecial'
    | '/pages/location'
    | '/pages/overview'
    | '/pages/premium'
    | '/pages/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/board/news_list'
    | '/pages/brand'
    | '/pages/changeinfo'
    | '/pages/contact'
    | '/pages/docnormal'
    | '/pages/docspecial'
    | '/pages/location'
    | '/pages/overview'
    | '/pages/premium'
    | '/pages/video'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/board/news_list'
    | '/pages/brand'
    | '/pages/changeinfo'
    | '/pages/contact'
    | '/pages/docnormal'
    | '/pages/docspecial'
    | '/pages/location'
    | '/pages/overview'
    | '/pages/premium'
    | '/pages/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  BoardNews_listRoute: typeof BoardNews_listRoute
  PagesBrandRoute: typeof PagesBrandRoute
  PagesChangeinfoRoute: typeof PagesChangeinfoRoute
  PagesContactRoute: typeof PagesContactRoute
  PagesDocnormalRoute: typeof PagesDocnormalRoute
  PagesDocspecialRoute: typeof PagesDocspecialRoute
  PagesLocationRoute: typeof PagesLocationRoute
  PagesOverviewRoute: typeof PagesOverviewRoute
  PagesPremiumRoute: typeof PagesPremiumRoute
  PagesVideoRoute: typeof PagesVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/news_list': {
      id: '/board/news_list'
      path: '/board/news_list'
      fullPath: '/board/news_list'
      preLoaderRoute: typeof BoardNews_listRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/brand': {
      id: '/pages/brand'
      path: '/pages/brand'
      fullPath: '/pages/brand'
      preLoaderRoute: typeof PagesBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/changeinfo': {
      id: '/pages/changeinfo'
      path: '/pages/changeinfo'
      fullPath: '/pages/changeinfo'
      preLoaderRoute: typeof PagesChangeinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/contact': {
      id: '/pages/contact'
      path: '/pages/contact'
      fullPath: '/pages/contact'
      preLoaderRoute: typeof PagesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/docnormal': {
      id: '/pages/docnormal'
      path: '/pages/docnormal'
      fullPath: '/pages/docnormal'
      preLoaderRoute: typeof PagesDocnormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/docspecial': {
      id: '/pages/docspecial'
      path: '/pages/docspecial'
      fullPath: '/pages/docspecial'
      preLoaderRoute: typeof PagesDocspecialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/location': {
      id: '/pages/location'
      path: '/pages/location'
      fullPath: '/pages/location'
      preLoaderRoute: typeof PagesLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/overview': {
      id: '/pages/overview'
      path: '/pages/overview'
      fullPath: '/pages/overview'
      preLoaderRoute: typeof PagesOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/premium': {
      id: '/pages/premium'
      path: '/pages/premium'
      fullPath: '/pages/premium'
      preLoaderRoute: typeof PagesPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/video': {
      id: '/pages/video'
      path: '/pages/video'
      fullPath: '/pages/video'
      preLoaderRoute: typeof PagesVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  BoardNews_listRoute: BoardNews_listRoute,
  PagesBrandRoute: PagesBrandRoute,
  PagesChangeinfoRoute: PagesChangeinfoRoute,
  PagesContactRoute: PagesContactRoute,
  PagesDocnormalRoute: PagesDocnormalRoute,
  PagesDocspecialRoute: PagesDocspecialRoute,
  PagesLocationRoute: PagesLocationRoute,
  PagesOverviewRoute: PagesOverviewRoute,
  PagesPremiumRoute: PagesPremiumRoute,
  PagesVideoRoute: PagesVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
